作業目標
熟悉陣列維度轉換，並且會擷取需要資料
作業重點
使用reshap須注意order用法
where可以運用邏輯條件擷取資料

題目:
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
2.呈上題的array，找出被6除餘1的數的索引

In [1]:
import numpy as np

In [121]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
array1 = array1.reshape(5,6)
array1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [3]:
#2.呈上題的array，找出被6除餘1的數的索引

In [122]:
np.where(array1 % 3 == 1)

(array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([1, 4, 1, 4, 1, 4, 1, 4, 1, 4], dtype=int64))

### 上方是作業，下方是練習

In [1]:
import numpy as np

In [2]:
a = np.array([[0,1,2,3],
             [4,5,6,7],
             [8,9,10,11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
c=a.flatten()
c[3]=100
c

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [12]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
b[3]=100
b

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [15]:
a

array([[  0,   1,   2, 100],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [16]:
a.ravel(order="C")

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [17]:
a.ravel(order="F")

array([  0,   4,   8,   1,   5,   9,   2,   6,  10, 100,   7,  11])

In [18]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
a.size

15

In [21]:
a.reshape((3,6))

ValueError: cannot reshape array of size 15 into shape (3,6)

In [22]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
a.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [29]:
b = a.reshape((3,5))
b[0,2]=100
b

array([[  0,   1, 100,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [30]:
a

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [31]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
b.size

15

In [35]:
b.resize((3,6),refcheck=False)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14,  0,  0,  0]])

In [36]:
b.resize(3,refcheck=False)
b

array([0, 1, 2])

In [37]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [38]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
a = np.array([[[1,2,3],[4,5,6],
              [7,8,9],[10,11,12]]
             ,[[1,2,3],[4,5,6],
              [7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
a.shape

(2, 4, 3)

In [41]:
a.sum(axis=0)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [52]:
a = np.arange(12).reshape(2,6)
a[:,np.newaxis,:]

array([[[ 0,  1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10, 11]]])

In [51]:
a[:,np.newaxis,:].shape

(2, 1, 6)

In [53]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [54]:
b = np.arange(12).reshape(2,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [55]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
b = np.arange(6).reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [57]:
np.concatenate((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [59]:
c = np.arange(10).reshape(5,2)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [60]:
np.stack((a,c),axis=1)

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]],

       [[8, 9],
        [8, 9]]])

In [63]:
np.hstack((a,c))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [64]:
np.vstack((a,b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [65]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [66]:
np.split(a,5)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]])]

In [68]:
np.split(a,[2,3])

[array([[0, 1],
        [2, 3]]),
 array([[4, 5]]),
 array([[6, 7],
        [8, 9]])]

In [69]:
b = np.arange(30).reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [70]:
np.hsplit(b,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

In [71]:
np.hsplit(b,[2,3,5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29]])]

In [72]:
np.vsplit(b,[2,4,6])

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([], shape=(0, 6), dtype=int32)]

In [73]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [74]:
for i in a:
    print(i)

0
1
2
3
4


In [76]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
for row in b:
    print(row)

[0 1 2]
[3 4 5]


In [78]:
for i in b.flat:
    print(i)

0
1
2
3
4
5


In [79]:
a = np.random.randint(1,20,10)
a

array([ 7,  5,  9, 16, 18,  8, 17,  6, 17, 18])

In [80]:
np.amax(a)

18

In [81]:
np.amin(a)

5

In [82]:
b = a.reshape(2,5)
b

array([[ 7,  5,  9, 16, 18],
       [ 8, 17,  6, 17, 18]])

In [84]:
np.amax(b,keepdims=True)

array([[18]])

In [85]:
b.max(axis=1)

array([18, 18])

In [86]:
np.amax(b,axis=1)

array([18, 18])

In [87]:
b.min(axis=0)

array([ 7,  5,  6, 16, 18])

In [88]:
np.random.seed(0)
a = np.random.randint(1,20,size=(3,4))
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [89]:
np.argmax(a)

7

In [90]:
np.argmax(a,axis=0)

array([0, 0, 2, 1], dtype=int64)

In [91]:
a.argmin()

2

In [92]:
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [93]:
np.where(a>10)

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 3, 2], dtype=int64))

In [94]:
np.where(a>10,"Y","N")

array([['Y', 'Y', 'N', 'N'],
       ['N', 'N', 'N', 'Y'],
       ['N', 'N', 'Y', 'N']], dtype='<U1')

In [95]:
np.random.seed(2)
a = np.random.randint(0,5,10)
a

array([0, 0, 3, 2, 3, 0, 2, 1, 3, 2])

In [96]:
np.nonzero(a)

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [98]:
a.nonzero()

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [99]:
np.random.seed(3)
a = np.random.randint(0,20,10)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6])

In [100]:
np.sort(a)

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [101]:
a.argsort()

array([3, 1, 9, 2, 7, 0, 5, 8, 6, 4], dtype=int64)

In [103]:
a.sort()
a

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [104]:
b = np.random.randint(0,20,size=(5,4))
b

array([[ 0, 12,  7, 14],
       [17,  2,  2,  1],
       [19,  5,  8, 14],
       [ 1, 10,  7, 11],
       [ 1, 15, 16,  5]])

In [105]:
np.sort(b,axis=0)

array([[ 0,  2,  2,  1],
       [ 1,  5,  7,  5],
       [ 1, 10,  7, 11],
       [17, 12,  8, 14],
       [19, 15, 16, 14]])

In [107]:
c = np.random.randint(0,100000000,1000000)
np.sort(c,kind='heapsort')

array([      26,       58,       66, ..., 99999884, 99999914, 99999944])