### 作業目標:
嘗試練習log的函式並應用
作業重點:
學員需要複習log的轉換方式
熟悉運用指數函數以及對數函數

題目:
運用投影片中的分貝公式回答下列問題。
1.正常的談話的聲壓為20000微巴斯卡，請問多少分貝?
2.30分貝的聲壓會是50分貝的幾倍?

In [ ]:
import numpy as np

In [54]:
# 1.正常的談話的聲壓為 20000 微巴斯卡，請問多少分貝?
#請寫下程式
v1 = 20000
v0 = 20
Gdb = 20 * np.log10(v1/v0)
Gdb

60.0

In [56]:
# 這題一開始解不出來，直接去看別人的解法
# 2.30 分貝的聲壓會是 50 分貝的幾倍?
#公式移項過後可以得到 V1 = ?
#請寫下程式
# 30 = 20 * np.log10(v30/20) => 10**(30/20) == v30/20 => v30 == 10**(30/20)*20
V30 = 10**(30/20)*20
# 50 = 20 * np.log10(v50/20) => 10**(50/20) == v50/20 => v50 == 10**(50/20)*20
V50 = 10**(50/20)*20
V30 / V50 

0.09999999999999999

### 上方是作業，下方是練習

In [3]:
import numpy as np

In [2]:
np.add(1.0,3.0)

4.0

In [14]:
a = np.array([1,2,3,4,5])
b = np.array([2,2,2,2,2])
a+b

array([3, 4, 5, 6, 7])

In [4]:
np.add(a,b)

array([3, 4, 5, 6, 7])

In [5]:
a-b

array([-1,  0,  1,  2,  3])

In [6]:
a*b

array([ 2,  4,  6,  8, 10])

In [7]:
a/b

array([0.5, 1. , 1.5, 2. , 2.5])

In [8]:
a%b

array([1, 0, 1, 0, 1], dtype=int32)

In [4]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
d = 3
c * d

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
e = np.random.randint(1,10,20).reshape(2, 10)
e

array([[5, 4, 9, 3, 6, 3, 8, 2, 3, 3],
       [8, 1, 3, 9, 2, 4, 9, 4, 4, 2]])

In [7]:
c + e

array([[ 5,  5, 11,  6, 10,  8, 14,  9, 11, 12],
       [ 8,  2,  5, 12,  6,  9, 15, 11, 12, 11]])

In [15]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
a.sum()

45

In [10]:
np.sum(a,axis=0)

array([ 5,  7,  9, 11, 13])

In [11]:
np.power(2,3)

8

In [16]:
np.power(a,b)

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]], dtype=int32)

In [17]:
e ** c

array([[     1,      4,     81,     27,   1296,    243, 262144,    128,
          6561,  19683],
       [     1,      1,      9,    729,     16,   1024, 531441,  16384,
         65536,    512]], dtype=int32)

In [20]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [22]:
np.e

2.718281828459045

In [23]:
np.exp(1)

2.718281828459045

In [24]:
np.exp(np.arange(5))

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [25]:
np.log10(np.array([1, 10, 100, 1000, 10000]))

array([0., 1., 2., 3., 4.])

In [26]:
np.log(9) /np.log(3)

2.0

In [27]:
import warnings
warnings.filterwarnings('ignore')

In [28]:
np.log([-1,1,2])

array([       nan, 0.        , 0.69314718])

In [29]:
a = np.array([1.65, 1.55, -3.57, 2.0])

In [31]:
np.round(a,decimals=1)

array([ 1.6,  1.6, -3.6,  2. ])

In [32]:
np.rint(a)

array([ 2.,  2., -4.,  2.])

In [33]:
np.trunc(a)

array([ 1.,  1., -3.,  2.])

In [34]:
np.floor(a)

array([ 1.,  1., -4.,  2.])

In [35]:
np.ceil(a)

array([ 2.,  2., -3.,  2.])

In [36]:
np.fix(a)

array([ 1.,  1., -3.,  2.])

In [37]:
a

array([ 1.65,  1.55, -3.57,  2.  ])

In [49]:
np.abs(a)

array([1.65, 1.55, 3.57, 2.  ])

In [51]:
np.fabs(1+2j)

TypeError: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''