作業目標
熟悉邏輯運算
作業重點
五大類邏輯函式與其對應的函式操作

題目:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，運用上列數據回答下列問題。

有多少學生英文成績比數學成績高?
是否全班同學最高分都是國文?

In [1]:
import numpy as np

In [31]:
#1.有多少學生英文成績比數學成績高?
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

count = 0
for i in range(english_score.size):
    if english_score[i] > math_score[i]:
        count += 1
print(count)
    


3


In [3]:
#2.是否全班同學最高分都是國文?
count = 0
for i in range(chinese_score.size):
    if chinese_score[i] > english_score[i] and :
        count += 1
print(count)

上面是作業，下面是解答

In [2]:
import numpy as np

In [5]:
np.isnan(np.array([1.0,np.nan,3.0]))

array([False,  True, False])

In [6]:
np.isfinite(1.0)

True

In [7]:
np.isfinite(np.nan)

False

In [8]:
np.isinf([np.inf,-np.inf,1.0,np.nan,np.PINF])

array([ True,  True, False, False,  True])

In [9]:
np.isposinf(np.PINF)

True

In [10]:
np.isneginf(np.NINF),np.isneginf(np.nan)

(True, False)

In [12]:
np.isnat(np.array(["NaT","2020-06-26"],dtype="datetime64[ns]"))

array([ True, False])

In [15]:
a = np.array([1, 2, 3])
np.isscalar(a[2])

True

In [16]:
np.isscalar(a)

False

In [17]:
np.isscalar(np.pi)

True

In [18]:
np.isscalar(np.array(3.0))

False

In [3]:
b = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
np.isreal(b)

array([False,  True,  True,  True,  True, False])

In [4]:
np.iscomplex(b)

array([ True, False, False, False, False,  True])

In [5]:
np.iscomplexobj(b)

True

In [6]:
np.isrealobj(b)

False

In [7]:
np.isrealobj(np.array([1,2.0,3.1]))

True

In [8]:
np.array_equal(np.array([1,2,3]),np.array([1,2,3]))

True

In [9]:
np.array_equal(np.array([1,2,3]),np.array([1,2,5]))

False

In [10]:
np.array_equiv(np.array([1,2,3]), np.array([1,2,3]))

True

In [12]:
np.array_equiv(np.array([1,2,3]), np.array([[1,2,3],[1,2,3]]))

True

In [13]:
np.array_equiv(np.array([1,1,1]),np.array([1]))

True

In [14]:
np.equal(np.array([1,2,3]),np.array([1,2,3]))

array([ True,  True,  True])

In [15]:
np.equal(np.array([1,1,1]),np.ones(1))

array([ True,  True,  True])

In [16]:
np.not_equal([1,2],[[1,3],[1,4]])

array([[False,  True],
       [False,  True]])

In [18]:
x = np.array([True, True, False, False])
y = np.array([True, False, True, False])

In [19]:
np.logical_and(x, y)

array([ True, False, False, False])

In [21]:
np.logical_or(x,y)

array([ True,  True,  True, False])

In [22]:
np.logical_not(x)

array([False, False,  True,  True])

In [23]:
np.logical_xor(x,y)

array([False,  True,  True, False])

In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [25]:
np.logical_and(a>1,a<4)

array([False, False,  True,  True, False])

In [26]:
np.all([-1,np.nan,5])

True

In [27]:
np.all([-1,4,0])

False

In [29]:
np.any([[True,False],[True,True]])

True

In [30]:
np.any([[True,False],[False,False]],axis=0)

array([ True, False])