english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,np.nan,60])

chinese_score = np.array([65,90,82,72,66,77])



上 3 列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文 55 分、數學 60 分、國文 65 分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。

In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [3]:
#1 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略？
english_mean = np.nanmean(english_score)
english_max = np.nanmax(english_score)
english_min = np.nanmin(english_score)
english_std = np.nanstd(english_score)

math_mean = np.nanmean(math_score)
math_max = np.nanmax(math_score)
math_min = np.nanmin(math_score)
math_std = np.nanstd(math_score)

chinese_mean = np.nanmean(chinese_score)
chinese_max = np.nanmax(chinese_score)
chinese_min = np.nanmin(chinese_score)
chinese_std = np.nanstd(chinese_score)

print("英文成績:")
print("平均值:{0}，最高分:{1}，最低分:{2}，標準差:{3}".format(english_mean,english_max,english_min,english_std))

print("數學成績:")
print("平均值:{0}，最高分:{1}，最低分:{2}，標準差:{3}".format(math_mean,math_max,math_min,math_std))

print("中文成績:")
print("平均值:{0}，最高分:{1}，最低分:{2}，標準差:{3}".format(chinese_mean,chinese_max,chinese_min,chinese_std))

英文成績:
平均值:67.16666666666667，最高分:89，最低分:48，標準差:13.433995020924426
數學成績:
平均值:66.6，最高分:85.0，最低分:60.0，標準差:9.707728879609279
中文成績:
平均值:75.33333333333333，最高分:90，最低分:65，標準差:8.825468196582484


In [4]:
#2 第五位同學補考數學後成績為 55，請計算補考後數學成績平均、最大值、最小值、標準差？
math_score[4] = 55
math_mean = np.nanmean(math_score)
math_max = np.nanmax(math_score)
math_min = np.nanmin(math_score)
math_std = np.nanstd(math_score)

print("數學成績:")
print("平均值:{0}，最高分:{1}，最低分:{2}，標準差:{3}".format(math_mean,math_max,math_min,math_std))

數學成績:
平均值:64.66666666666667，最高分:85.0，最低分:55.0，標準差:9.860132971832694


In [5]:
#3 用補考後資料找出與國文成績相關係數最高的學科？
np.corrcoef(chinese_score,english_score)
np.corrcoef(chinese_score,math_score)

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

### 上方是作業

In [6]:
import numpy as np

In [7]:
np.random.seed(1)
a = np.random.randint(1,10,6).reshape(2,3)
b = np.random.randint(1,5,3)

In [8]:
a

array([[6, 9, 6],
       [1, 1, 2]])

In [9]:
b

array([1, 4, 2])

In [10]:
np.maximum(a,b)

array([[6, 9, 6],
       [1, 4, 2]])

In [11]:
np.minimum(a,b)

array([[1, 4, 2],
       [1, 1, 2]])

In [12]:
np.maximum(a,[np.nan,0,np.nan])

array([[nan,  9., nan],
       [nan,  1., nan]])

In [13]:
np.fmax(a,b)

array([[6, 9, 6],
       [1, 4, 2]])

In [14]:
np.fmin([np.nan,3,np.nan],[np.nan,np.nan,np.nan])

array([nan,  3., nan])

In [15]:
np.nanmax([1,2,np.nan,3])

3.0

In [16]:
np.nanmax([np.nan,np.nan])

<ipython-input-16-d80b3982e42e>:1: RuntimeWarning: All-NaN axis encountered
  np.nanmax([np.nan,np.nan])


nan

In [17]:
p = np.arange(1,20).astype('float32')
p

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19.], dtype=float32)

In [18]:
np.percentile(p,[30,60])

array([ 6.4, 11.8])

In [19]:
p[5] = np.nan
p[9] = np.nan
p[15] = np.nan

In [20]:
p

array([ 1.,  2.,  3.,  4.,  5., nan,  7.,  8.,  9., nan, 11., 12., 13.,
       14., 15., nan, 17., 18., 19.], dtype=float32)

In [21]:
np.nanpercentile(p,50)

10.0

In [22]:
np.percentile(p,50)

nan

In [23]:
q = np.array([23,  2,  1, 18,  9, 25, 14, 48, 43,  9, 31,  8,  4,  7, 22,  4,  5, 25, 44, 13])
q

array([23,  2,  1, 18,  9, 25, 14, 48, 43,  9, 31,  8,  4,  7, 22,  4,  5,
       25, 44, 13])

In [24]:
np.quantile(q,0.25)

6.5

In [25]:
q = np.array([23,  2,  1, np.nan,  9, 25, np.nan, 48, 43,  9, 31,  np.nan,  4,  7, np.nan,  4,  5, 25, 44, 13]).reshape(5, 4)
q

array([[23.,  2.,  1., nan],
       [ 9., 25., nan, 48.],
       [43.,  9., 31., nan],
       [ 4.,  7., nan,  4.],
       [ 5., 25., 44., 13.]])

In [26]:
np.nanquantile(q,0.25,axis=0,keepdims=True)

array([[ 5. ,  7. , 16. ,  8.5]])

In [27]:
a = np.array([23,  2,  1, np.nan,  9, 25, np.nan, 
              48, 43,  9, 31,  np.nan]).reshape(3, 4)
a

array([[23.,  2.,  1., nan],
       [ 9., 25., nan, 48.],
       [43.,  9., 31., nan]])

In [28]:
np.mean(a)

nan

In [29]:
if not np.isnan(np.sum(a)):
    print(np.mean(a))
else:
    print(np.nanmean(a))

21.22222222222222


In [30]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
np.average(a,axis=1,weights=[0.25,0.75])

array([0.75, 2.75, 4.75])

In [32]:
np.average(a,axis=1,weights=[0,0])

ZeroDivisionError: Weights sum to zero, can't be normalized

In [ ]:
np.random.seed(5)
m = np.random.randint(1,50,15).reshape(3,5)
m

In [ ]:
np.median(m,axis=1)

In [ ]:
np.nanmedian(np.array([[36,15,np.nan,39,17],
                      [np.nan,9,37,np.nan,28],
                      [49,np.nan,17,8,13]]), axis=1)

In [ ]:
s = np.array([[1,2],[3,4]])
np.std(s)

In [ ]:
v = np.array([[1,2],[3,4]])
np.var(a)

In [ ]:
np.var(a,axis=0)

In [ ]:
np.var(a,axis=1)

In [ ]:
x = np.random.randint(1,20,10).reshape(2,5)
x

In [ ]:
np.corrcoef(x)

In [ ]:
np.correlate([1,2,3],[0,1])

In [ ]:
x = np.array([[0,1,2],[2,1,0]])
np.cov(x)

In [ ]:
a = np.random.randint(0,10,100).reshape(10,10)
a

In [ ]:
hist,bin_edges = np.histogram(a,bins=9)
hist,bin_edges

In [ ]:
unique,counts = np.unique(a,return_counts=True)

In [ ]:
unique,counts

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.hist(a.reshape(-1), bins=9)

In [ ]:
x = np.array([0.5,6.2,3.0,1.7])
bins = np.array([0.0,1.0,2.5,4.0,10.0])

In [ ]:
inds = np.digitize(x,bins)
inds