作業目標
讀取存取陣列資料
作業重點
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:

將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [2]:
import numpy as np

In [53]:
#1. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

with open('hw6.npz','wb') as f:
    np.savez(f,array1=array1,array2=array2)


In [59]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
npzfile = np.load('hw6.npz')

array3 = np.array([7,8,9])
with open('hw6.npz','wb') as f:
    np.savez(f,array1=array1,array2=array2,array3=array3)
npzfile['array3']

array([7, 8, 9])

### ---上方是作業，下方是練習---

In [5]:
with open('one_array.npy','wb') as f:
    np.save(f,np.array([1,2]))

In [9]:
np.load('one_array.npy')

array([1, 2])

In [11]:
with open('test.npy','wb') as f:
    np.save(f,np.array([1,2]))
    np.save(f,np.array([1,3]))
    np.save(f,np.array([1,4]))
    np.save(f,np.array([1,3]))

In [15]:
with open('test.npy','rb') as f:
    a = np.load(f)
    b = np.load(f)
    c = np.load(f)
    d = np.load(f)

print(a,b,c,d)

[1 2] [1 3] [1 4] [1 3]


In [17]:
x = np.arange(10)
y = np.array([1,2,3])
z = np.random.rand(10)

with open('multi_array.npz','wb') as f:
    np.savez(f,array1=x,array2=y,array3=z)

In [18]:
npzfile = np.load('multi_array.npz')
type(npzfile)

numpy.lib.npyio.NpzFile

In [19]:
npzfile.files

['array1', 'array2', 'array3']

In [20]:
print(npzfile['array1'])
print(npzfile['array2'])
print(npzfile['array3'])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.43028883 0.59653772 0.77481726 0.98819548 0.4603047  0.15129748
 0.59654837 0.90968444 0.33195769 0.79619602]


In [21]:
x = y = z = np.arange(0.0,5.0,1.0)
x

array([0., 1., 2., 3., 4.])

In [22]:
y = np.arange(10).reshape(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.savetxt('test.out',[x],delimiter=',')

In [ ]:
# %load test.out
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00


In [26]:
np.savetxt('test.gz',[x],delimiter=',')

In [27]:
np.savetxt('test.csv',y,delimiter=',')

In [ ]:
# %load test.csv
0.000000000000000000e+00,1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00


In [29]:
np.savetxt('test.out',x,fmt='%1.4e',delimiter=',',header='this is,\nheader', footer='this is footer')

In [ ]:
# %load test.out
# this is,
# header
0.0000e+00
1.0000e+00
2.0000e+00
3.0000e+00
4.0000e+00
# this is footer


In [31]:
np.loadtxt('test.out',delimiter=',',dtype='f4')

array([0., 1., 2., 3., 4.], dtype=float32)

In [32]:
np.genfromtxt("test.csv",delimiter=",")

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [33]:
np.genfromtxt("test.gz",delimiter=",")

array([0., 1., 2., 3., 4.])

In [34]:
np.genfromtxt(["1","2","abc","4","5"])

array([ 1.,  2., nan,  4.,  5.])

In [37]:
from io import StringIO

data = u"  1  2  3\n  4  5 67\n890123  4"
np.genfromtxt(StringIO(data), delimiter=3)

array([[  1.,   2.,   3.],
       [  4.,   5.,  67.],
       [890., 123.,   4.]])

In [38]:
data = u"123456789\n   4  7 9\n   4567 9"
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))

array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

In [39]:
%load names.txt

ValueError: 'names.txt' was not found in history, as a file, url, nor in the user namespace.